# Generated by Django 6.0.2 on 2026-02-13 23:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('method', models.CharField(max_length=10)),
                ('headers', models.JSONField(default=dict)),
                ('body', models.JSONField(blank=True, default=dict, null=True)),
                ('raw_body', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
